# Generated by Django 3.2.7 on 2021-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposaltitle', '0002_proposetitle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposetitle',
            name='status',
        ),
        migrations.AddField(
            model_name='titlecomment',
            name='status',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
