# Generated by Django 3.2.7 on 2021-09-30 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposaltitle', '0005_auto_20210930_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titlecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
