# Generated by Django 3.2.7 on 2021-10-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidetopic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='guide/%Y-%m-%d')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guide/')),
                ('topic', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.guide_topic')),
            ],
        ),
    ]
