# Generated by Django 3.2.7 on 2021-12-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='pdf',
            new_name='file',
        ),
    ]
