# Generated by Django 3.2.7 on 2021-11-27 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0008_remove_rubrix_timestamp'),
        ('manuscriptevaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubrixEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rubrix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.rubrix')),
                ('student_submit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.studentsubmit')),
            ],
        ),
        migrations.DeleteModel(
            name='EvaluationGrade',
        ),
    ]
