# Generated by Django 3.2.7 on 2021-11-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscriptevaluations', '0002_auto_20211128_0405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RubrixEvaluation',
        ),
    ]
