# Generated by Django 3.2.7 on 2021-11-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_delete_rubrix'),
        ('manuscriptevaluations', '0004_evaluationgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationgrade',
            name='submission_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.submissiontitle'),
        ),
        migrations.AlterField(
            model_name='evaluationgrade',
            name='N',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluationgrade',
            name='PF',
            field=models.BooleanField(null=True),
        ),
    ]
