# Generated by Django 3.2.7 on 2021-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscriptevaluations', '0006_remove_evaluationgrade_submission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationgrade',
            name='PF',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
