# Generated by Django 3.2.7 on 2021-12-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscriptevaluations', '0007_alter_evaluationgrade_pf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationgrade',
            name='N',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='evaluationgrade',
            name='PF',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
