# Generated by Django 3.2.7 on 2021-12-03 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0015_alter_studentsubmit_timestamp'),
        ('manuscriptevaluations', '0008_auto_20211203_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationgrade',
            name='evaluator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationgrade',
            name='student_submission',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.studentsubmit'),
        ),
    ]
