# Generated by Django 3.2.7 on 2021-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscriptevaluations', '0009_auto_20211203_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationgrade',
            name='N',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='evaluationgrade',
            name='PF',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
