# Generated by Django 3.2.7 on 2021-10-08 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=225)),
                ('mem1_fn', models.CharField(max_length=1000, null=True)),
                ('mem1_ln', models.CharField(max_length=1000, null=True)),
                ('mem1_email', models.CharField(max_length=1000, null=True)),
                ('mem2_fn', models.CharField(max_length=1000, null=True)),
                ('mem2_ln', models.CharField(max_length=1000, null=True)),
                ('mem2_email', models.CharField(max_length=1000, null=True)),
                ('mem3_fn', models.CharField(max_length=1000, null=True)),
                ('mem3_ln', models.CharField(max_length=1000, null=True)),
                ('mem3_email', models.CharField(max_length=1000, null=True)),
                ('mem4_fn', models.CharField(max_length=1000, null=True)),
                ('mem4_ln', models.CharField(max_length=1000, null=True)),
                ('mem4_email', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
