# Generated by Django 3.2.7 on 2021-11-20 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposalgroup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mem1_email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem1_fn',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem1_ln',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem2_email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem2_fn',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem2_ln',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem3_email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem3_fn',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem3_ln',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem4_email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem4_fn',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem4_ln',
        ),
        migrations.AddField(
            model_name='group',
            name='mem1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='mem2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='mem3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='mem4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
