# Generated by Django 3.2.7 on 2021-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0002_alter_adviserandpanelist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserandpanelist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
