# Generated by Django 3.2.7 on 2021-09-30 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0003_alter_adviserandpanelist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserandpanelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adviserandpanelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
