# Generated by Django 3.2.7 on 2021-10-08 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('submission_detail', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_content', models.TextField(blank=True, null=True)),
                ('pdf_submit', models.FileField(blank=True, max_length=500, null=True, upload_to='submissions/%Y-%m-%d/')),
                ('filename', models.CharField(max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='no submission', max_length=100)),
                ('submission_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submissiontitle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
