# Generated by Django 3.2.7 on 2021-11-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmit',
            name='for_eval_submit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='submissiontitle',
            name='for_evaluation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='CommentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('submission_content', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.studentsubmit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
