# Generated by Django 3.2.7 on 2021-11-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20211104_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
