# Generated by Django 3.2.7 on 2021-11-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0004_alter_submissiontitle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rub_title', models.CharField(max_length=100)),
                ('rub_description', models.CharField(max_length=250)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_submit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.studentsubmit')),
                ('submission_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submissiontitle')),
            ],
        ),
    ]
