# Generated by Django 3.2.7 on 2021-11-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_rubrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrix',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='rubrix',
            name='student_submit',
        ),
    ]
