# Generated by Django 3.2.7 on 2021-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20211128_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrix',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
