# Generated by Django 3.2.7 on 2021-11-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_rubrix_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrix',
            name='timestamp',
        ),
    ]
