# Generated by Django 3.2.7 on 2021-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20211128_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrix',
            name='grade',
            field=models.FloatField(null=True),
        ),
    ]
