# Generated by Django 3.2.7 on 2021-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_studentsubmit_type_of_eval_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmit',
            name='type_of_eval_grade',
        ),
        migrations.AddField(
            model_name='submissiontitle',
            name='type_of_eval_grade',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
