# Generated by Django 3.2.7 on 2021-12-03 20:27

from django.db import migrations, models
import submissions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_alter_studentsubmit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmit',
            name='pdf_submit',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='submissions/%Y-%m-%d/', validators=[submissions.validators.validate_file_extension]),
        ),
    ]
