# Generated by Django 3.2.7 on 2021-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_alter_studentsubmit_pdf_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmit',
            name='sub_evaluator',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
