# Generated by Django 3.2.7 on 2021-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_studentsubmit_sub_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmit',
            name='if_seen',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
