# Generated by Django 3.2.7 on 2021-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(default='B16C31', max_length=6, unique=True),
        ),
    ]
