# Generated by Django 3.2.7 on 2021-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_code_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBatchUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(blank=True, null=True, upload_to='batchupload/%Y-%m-%d')),
            ],
        ),
    ]
