# Generated by Django 3.2.7 on 2021-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20211121_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group_name',
            field=models.CharField(default='None', max_length=250, null=True),
        ),
    ]
