# Generated by Django 3.2.7 on 2021-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposaltitle', '0002_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='reply',
            field=models.TextField(max_length=1000),
        ),
    ]
