# Generated by Django 3.2.7 on 2021-12-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposaltitle', '0003_alter_commentreply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposetitle',
            name='edited',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
