# Generated by Django 3.2.7 on 2021-10-08 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
        ('proposaltitle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserAndPanelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('final_title', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to='register.userprofile')),
                ('panel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel1', to='register.userprofile')),
                ('panel2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel2', to='register.userprofile')),
                ('panel3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel3', to='register.userprofile')),
                ('proposed_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposaltitle.proposetitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
