# Generated by Django 3.2.7 on 2021-11-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0002_adviserrequest_panel1request_panel2request_panel3request'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserrequest',
            name='proposedtitle',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='adviserrequest',
            name='titledescription',
            field=models.TextField(default=None),
        ),
    ]
