# Generated by Django 3.2.7 on 2021-11-18 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0003_auto_20211119_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserrequest',
            name='finaltitle',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='adviserrequest',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='panel1request',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='panel2request',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='panel3request',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
