# Generated by Django 3.2.7 on 2021-11-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0004_auto_20211119_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
