# Generated by Django 3.2.7 on 2021-11-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0006_auto_20211119_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserrequest',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panel1request',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panel2request',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panel3request',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
