# Generated by Django 3.2.7 on 2021-11-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('proposalpanelists', '0007_auto_20211119_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserandpanelist',
            name='panel1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel1', to='register.userprofile'),
        ),
        migrations.AlterField(
            model_name='adviserandpanelist',
            name='panel2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel2', to='register.userprofile'),
        ),
        migrations.AlterField(
            model_name='adviserandpanelist',
            name='panel3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectpanel3', to='register.userprofile'),
        ),
    ]
