# Generated by Django 3.2.7 on 2021-11-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0008_auto_20211119_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_adviser', models.IntegerField(default=10, max_length=10)),
                ('as_panelist', models.IntegerField(default=10, max_length=10)),
            ],
        ),
    ]
