# Generated by Django 3.2.7 on 2021-11-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposalpanelists', '0010_auto_20211126_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitation',
            old_name='as_adviser',
            new_name='limit',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='as_panelist',
        ),
    ]
