# Generated by Django 3.2.7 on 2021-12-02 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposalpanelists', '0011_auto_20211126_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel2request',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel2name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel2request',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='panel2request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
