# Generated by Django 3.2.7 on 2021-12-02 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposalpanelists', '0012_auto_20211202_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserrequest',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adviserrequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='adviserrequest',
            name='titledescription',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adviserrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel1request',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel1name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel1request',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='panel1request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel3request',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel3name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel3request',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='panel3request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
